### ISSUE TITLE
PackageCode length

### ISSUE THREAD

**Issue by cmsdroff** [dcsaorg/DCSA-Information-Model#421]
For some type of package (mainly IBC's) the character limit of 3 is not sufficient, I suggest it needs to be increased to 5.

I created the schema for the Shipping Instruction which highlighted this as below, 
```
"packageCode":{
    "maxLength":3,
    "type":"string",
    "description":"The unique identifier for the package type"
},
```

Its in the IM sql
```
CREATE TABLE dcsa_im_v3_0.package_code (
    package_code varchar(3) PRIMARY KEY,
    package_code_description varchar(50) NOT NULL
);
```

The UN package type codes are ok under this, but in the chemical industry we often see package type codes for IBC that are 4-5 characters i.e. `13H3` 

An easy to digest reference point can be seen here:

* https://www.c-point.be/file/downloads/packaging_codes_en.pdf

followed by a few more detailed descriptions:
* https://unece.org/DAM/trans/danger/publi/adr/adr2005/English/Part6_ch6-5.pdf
* https://shashikallada.com/imdg-code-awareness-series-3-use-of-packaging-and-ibcs/ (see section under `Construction and testing of packagings and IBCS`)

Im unsure where best to modify for a PR, as its in use in schemas and the db reference example, and probably needs some thought by DCSA members.

**Comment by HenrikHL** [comment]
Hi @cmsdroff,

As always - thank you for the headsup - I will have our business experts look into this and get back to you as soon as I know something.

/Henrik

**Comment by HenrikHL** [comment]
Hi again @cmsdroff,

Business agrees with you - and I have already updated the packageCode from `3` characters --> `5` characters. The update is visible in the [EBL 3.0.0 Beta 1 API](https://app.swaggerhub.com/apis/dcsaorg/DCSA_EBL/3.0.0-Beta-1). Please be aware that the packageCode has been moved into the `outerPacking` object.

Thanks for your input - and I am sad we didn't meet up during the DCSA week - maybe next time ;-)

**Comment by cmsdroff** [comment]
@HenrikHL 

> Thanks for your input - and I am sad we didn't meet up during the DCSA week - maybe next time ;-)

Apologies for not finding each other, I left Wednesday evening but next time for sure we will meet up!
